modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Viola-Siemens/Advanced-Enchantments/issues"

[[mods]]
modId="advanced_enchantments"
version="${file.jarVersion}"
displayName="Advanced Enchantments"
logoFile="logo.png"
credits="Hexagram"
authors="Liu Dongyu, Mnibr"
description='''
This mod adds advanced versions for some of the vanilla enchantments.

Channeling II: causes a lightning bolt wherever and whenever it is after hitting an entity.
Silk Touch II: you can mine spawners, reinforced deepslate, budding amethyst and some other blocks (with nbt!).
Flame II: makes entities burns longer time after hit by arrows.
Infinity II: also makes spectral arrows and tipped arrows infine.

And it also adds an enchantment:

Damp (for chestplates and elytras): you can use tridents with riptide enchantment, take the conduit power effect from conduit in any case, even not in water.
'''
[[dependencies.advanced_enchantments]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.advanced_enchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
